url: https://vikasdhiman.info
baseurl: /ECE275-F23-Sequential-Logic
remote_theme:  samarsault/plainwhite-jekyll
title: Sequential Logic Systems (ECE275) at the University of Maine
author: Vikas Dhiman
description: Sequential Logic Systems (ECE275) at the University of Maine
show_excerpts: true

# Build settings
markdown: kramdown
permalink: pretty
paginate: 10


header_pages:
  - syllabus.md
  - labnotes.md
  - category/lecture


plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-remote-theme

plainwhite:
  name: Sequential Logic Systems (ECE275)
  tagline: |
     Boolean algebra, Flip-flops, K-Maps, Verilog

  sitemap: true

  search: true

  html_lang: "en"

  navigation:
    - title: Syllabus
      url: "/syllabus"
    - title: Schedule
      url: "https://docs.google.com/spreadsheets/d/e/2PACX-1vTjyw0_zWfPbG3yFm_hv6XIx2Q4hWhC7oQSIYzZ2Y3aEvE9G4f0CxxkdAaydcUVv24xyfUpCf-ldWKQ/pubhtml?gid=0&single=true"
    - title: Lab Notes
      url: "/labnotes"
    - title: Zoom Link
      url: "https://maine.zoom.us/j/88422320947?pwd=M1FmZWxxTHA2d3ozbWJab1RHYlBQZz09"
    - title: Similar courses
      url: "/similar-courses"

  portfolio_image: images/Transistor_Bistable_interactive_animated-en.svg
    
  condensed_mobile:
    - home
    - post
    - page
